[#ftl]
[@b.head/]
[#include "../status.ftl"/]
[@b.grid items=users var="user"]
  [@b.gridbar]
  function activateUser(isActivate){return action.multi("activate","确定提交?","isActivate="+isActivate);}
  bar.addItem("${b.text("action.modify")}",action.edit());
  bar.addItem("${b.text("action.export")}",action.exportData("code:账户,name:姓名,category.name:身份,beginOn:创建日期,endOn:结束日期","Xlsx","&fileName=用户信息"));
  [/@]
  [@b.row]
    [@b.boxcol/]
    [@b.col property="code" width="12%"]&nbsp;[@b.a href="!info?id=${user.id}"]${user.code}[/@][/@]
    [@b.col property="name" width="18%"/]
    [@b.col property="category.name" width="10%" /]
    [@b.col title="角色" width="27%"]
      [#assign members=[]]
      [#list user.roles?sort_by(['role','indexno']) as m][#if m.role.domain=domain] [#assign members=members+[m]][/#if][/#list]
      [#list members?sort_by(['role','indexno']) as m][#if m.member]${m.role.name}&nbsp;[/#if][/#list]
    [/@]
    [@b.col property="beginOn" title="user.beginOn-endOn" width="20%"]${user.beginOn}~${(user.endOn)!}[/@]
  [/@]
[/@]
[@b.foot/]
