[#ftl]
[@b.head/]
[@b.toolbar title="消息模板信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(template) theme="list"]
    [@b.select name="template.business.id" label="业务类型" value=template.business! items=businesses required="true"/]
    [@b.textfield name="template.name" label="名称" value=template.name! required="true" maxlength="80"/]
    [@b.radios name="template.todo" label="类型" value=template.todo items="1:代办提醒消息,0:办结通知消息"/]
    [@b.textarea cols="80" rows="2" label="消息标题" name="template.title" value=template.title! maxlength="500"/]
    [@b.textarea cols="80" rows="20" label="消息内容" name="template.contents" value=template.contents! maxlength="1000"/]
    [@b.textarea cols="80" rows="4" label="变量" name="template.variables" value=template.variables! maxlength="500" comment="v1=说明1;v2=说明2"/]
    [@b.textfield name="template.delayMinutes" label="延迟发送时间" value=template.delayMinutes! required="true" maxlength="10" comment="分钟"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
