[#ftl]
[@b.head/]
[@b.toolbar title="修改用户组信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(group) theme="list"]
    [@b.textfield name="group.indexno" label="层级编码" value=group.indexno! required="true" maxlength="80"/]
    [@b.textfield name="group.code" label="代码" value=group.code! required="true" maxlength="30"/]
    [@b.textfield name="group.name" label="名称" value=group.name! required="true" maxlength="80"/]
    [@b.radios label="是否启用"  name="group.enabled" value=group.enabled items="1:common.yes,0:common.no"/]
    [@b.select label="上级组" name="group.parent.id" value=(group.parent)! style="width:200px;"  items=parents  empty="..."/]
    [@b.select name="role.id" label="绑定角色" values=groupRoles items=roles multiple="true"/]
    [@b.textfield name="group.remark" label="说明" value=group.remark! maxlength="190"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[#list 1..10 as i]<br/>[/#list]
[@b.foot/]
