[#ftl]
[@b.head/]
[@b.toolbar title="新建/修改凭证"]bar.addBack();[/@]
<style>form.listform label.title{width:120px;}</style>
[@b.tabs]
  [@b.form action=save_action theme="list" action=b.rest.save(credential)]
    [@b.textfield name="credential.name" label="名称" value="${credential.name!}" required="true" maxlength="200"/]
    [@b.textfield name="credential.username" label="用户名" value="${credential.username!}" required="true" maxlength="200"/]
    [@b.textfield name="credential.password" label="密文" value="${credential.password!}" required="true" style="width:300px" maxlength="200"/]
    [@b.date name="credential.expiredAt" label="过期时间" value=credential.expiredAt required="true" format="datetime"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
