[#ftl]
[@b.head/]
[@b.toolbar title="新建/修改文档"]bar.addBack();[/@]
<style>form.listform label.title{width:120px;}</style>
[@b.form action=b.rest.save(doc) theme="list"   enctype="multipart/form-data"]
  [@b.textfield name="doc.name" label="标题" value="${doc.name!}" required="true" maxlength="100"/]
  [@b.select name="doc.app.id" label="应用" value="${(doc.app.id)!}" option="id,title" required="true" items=apps/]
  [@b.checkboxes name="category.id" label="面向用户" values=doc.categories required="true" items=categories/]
  [@b.radios name="doc.archived" label="是否归档" value=doc.archived required="true" /]
  [@b.field label="文件"]
    <input name="docfile" type="file"/>
  [/@]
  [@b.formfoot]
   [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
  [/@]
[/@]
[@b.foot/]
