[#ftl]
[@b.head/]
[@b.toolbar title="菜单配置"]bar.addBack();[/@]
[@b.form action=b.rest.save(channel) theme="list"]
  [@b.select name="channel.app.id" label="应用" value=(channel.app.id)! required="true" style="width:300px;" items=apps?sort_by("indexno") option="id,fullTitle"/]
  [@b.select name="channel.channelType.id" label="前端类型" value=(channel.channelType.id)! required="true" style="width:300px;" items=channelTypes option="id,title"/]
  [@b.textfield name="channel.base" label="上下文地址" value=channel.base! required="true" maxlength="200" style="width:400px" comment="缺省可填应用上下文地址"/]
  [@b.radios name="embedMode.id" label="嵌入方式" value=(channel.embedMode.id)!2 required="true" items="1:微前端,2:IFrame" comment="微前端参见 https://github.com/Tencent/wujie"/]
  [@b.radios name="channel.enabled" label="common.status" value=channel.enabled items="1:action.activate,0:action.freeze"/]
  [@b.formfoot]
    [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
  [/@]
[/@]
[@b.foot/]
