alter table ems.blb_blob_metas add constraint pk_b8cqbowbec39t4blmd3n8n074 primary key (id);
alter table ems.blb_profiles add constraint pk_4xq2aas8pre2k4gnyha4rrdc6 primary key (id);
alter table ems.cfg_app_groups add constraint idx_app_group unique (domain_id,name);
alter table ems.cfg_app_groups add constraint pk_j2j2ecvy0xos5dyc5bpvukvoo primary key (id);
alter table ems.cfg_app_types add constraint pk_tlb9nukbd5nakxiqdrb4lrrkg primary key (id);
alter table ems.cfg_app_types add constraint uk_5qmq81gd1xna4xeynxkdueqgu unique (name);
alter table ems.cfg_apps add constraint idx_app unique (domain_id,name);
alter table ems.cfg_apps add constraint pk_n9cedywnexu7mm5vrohyngxhi primary key (id);
alter table ems.cfg_credentials add constraint idx_credential unique (domain_id,name);
alter table ems.cfg_credentials add constraint pk_jqt3pjl6myepf89yf4vpl69lv primary key (id);
alter table ems.cfg_data_sources add constraint idx_datasource unique (app_id,name);
alter table ems.cfg_data_sources add constraint pk_hbg82rakrkc2sifjhhimm05p2 primary key (id);
alter table ems.cfg_dbs add constraint idx_db unique (domain_id,name);
alter table ems.cfg_dbs add constraint pk_60bu45dxjo2fv64icid8g60dr primary key (id);
alter table ems.cfg_dbs_properties add constraint pk_4hn9p4sx2tba0kn8c5m68bn5e primary key (db_id,value_,name);
alter table ems.cfg_domains add constraint idx_domain unique (org_id,hostname);
alter table ems.cfg_domains add constraint pk_endu524c1sjo6rfnwll8j7lgl primary key (id);
alter table ems.cfg_files add constraint pk_mqdje4swyctoaf3fghs8nh2h0 primary key (id);
alter table ems.cfg_orgs add constraint pk_p2falj90tsjnuf6cul4dtnwbr primary key (id);
alter table ems.cfg_portalets add constraint pk_lusy0ot4df8ad2ogi52ud31x0 primary key (id);
alter table ems.cfg_portalets_categories add constraint pk_3y5ll75dv63sbfxrt5djc3vst primary key (portalet_id,category_id);
alter table ems.log_business_logs add constraint pk_cq382d9fch1kobqqb4ejnngte primary key (id);
alter table ems.log_levels add constraint pk_5faxde0amku4jsvd65k03ipil primary key (id);
alter table ems.log_session_events add constraint pk_bfwebo3poax33vnkl9jdjfvnk primary key (id);
alter table ems.oa_docs add constraint pk_fc7xgtw2ph01nxnly6xdjj2ck primary key (id);
alter table ems.oa_docs_categories add constraint pk_t2xiuni4rx9kqxk3tl6ho27m0 primary key (doc_id,category_id);
alter table ems.oa_messages add constraint pk_72sarmx45o88vbj3vxqpxxuic primary key (id);
alter table ems.oa_news add constraint pk_eal2o84cuiediaeu3jpbj2rw8 primary key (id);
alter table ems.oa_notices add constraint pk_fd9lrfm32gdx34wnf5tkegwri primary key (id);
alter table ems.oa_notices_categories add constraint pk_ptniioqdxghbgxfb5nuxa8sok primary key (notice_id,category_id);
alter table ems.oa_notices_docs add constraint pk_g1q8sxttj2f38br6tshq0oyop primary key (notice_id,doc_id);
alter table ems.oa_notifications add constraint pk_rfa7ie0w95cyfm42bqiq8h59d primary key (id);
alter table ems.oa_sensitive_words add constraint pk_pjoqu9l57q76r8j9m8ohsd7bv primary key (id);
alter table ems.oa_todoes add constraint pk_9miwvbk7lnym5j8gloxvye2ov primary key (id);
alter table ems.se_app_permissions add constraint pk_d4wk578yt4vxs2wsxqw6wi44r primary key (id);
alter table ems.se_data_permissions add constraint pk_n3ngio8x079e9p038kn9208we primary key (id);
alter table ems.se_data_resources add constraint pk_m2lwng0xtvh944i0suv865sy primary key (id);
alter table ems.se_func_permissions add constraint pk_2oifsqty75lclhgfdusglmk4d primary key (id);
alter table ems.se_func_resources add constraint pk_glt9bssuurgayvpnxjupcsfqm primary key (id);
alter table ems.se_menus add constraint pk_c3931pkfbpf3uerudht53n8sj primary key (id);
alter table ems.se_menus_resources add constraint pk_gtyin0ge9irq6gy8qoupwbf3j primary key (menu_id,func_resource_id);
alter table ems.se_session_configs add constraint idx_session_config unique (domain_id,category_id);
alter table ems.se_session_configs add constraint pk_pp3vns65x9utg2vwtogp2cao8 primary key (id);
alter table ems.usr_accounts add constraint idx_account unique (user_id,domain_id);
alter table ems.usr_accounts add constraint pk_ls2nv75xnj31l3xpjbinw1w5f primary key (id);
alter table ems.usr_avatars add constraint pk_evhoecg5aoxqjlhw3emfuevip primary key (id);
alter table ems.usr_categories add constraint idx_user_category unique (org_id,name);
alter table ems.usr_categories add constraint pk_j6l4jh94s3ga3ncv15fg7kjl4 primary key (id);
alter table ems.usr_dimensions add constraint idx_dimension_name unique (domain_id,name);
alter table ems.usr_dimensions add constraint pk_17npsfcux6ix6kjq7r73roe2i primary key (id);
alter table ems.usr_group_members add constraint pk_9kgi9t31dhattii415hnqa8wp primary key (id);
alter table ems.usr_groups add constraint idx_group unique (org_id,name);
alter table ems.usr_groups add constraint pk_qiobgfi5x9uer99bb4an2klr5 primary key (id);
alter table ems.usr_groups_properties add constraint pk_ibxj802yxpljot7vm92k1y6th primary key (group_id,value_,dimension_id);
alter table ems.usr_password_configs add constraint idx_password_config unique (domain_id);
alter table ems.usr_password_configs add constraint pk_5qffiflvujhi6qpd4ww3doin5 primary key (id);
alter table ems.usr_profiles add constraint pk_l9sqo0uv1apeypxv0k3qchf8k primary key (id);
alter table ems.usr_profiles_properties add constraint pk_8erccmnnign5i91qbu5tpffw9 primary key (profile_id,value_,dimension_id);
alter table ems.usr_role_members add constraint pk_1vq74b9ympc9qdgjvqcghk84e primary key (id);
alter table ems.usr_roles add constraint idx_role_name unique (domain_id,name);
alter table ems.usr_roles add constraint pk_237n7fw14i3w0u34cwhapigb0 primary key (id);
alter table ems.usr_roles_properties add constraint pk_59m7apft4dpohfgp900cbkkip primary key (role_id,value_,dimension_id);
alter table ems.usr_roots add constraint pk_gpdqluxdt236rx6ft5wdoxiix primary key (id);
alter table ems.usr_users add constraint idx_user_code unique (org_id,code);
alter table ems.usr_users add constraint pk_q9yqro8mq11gawulqm149lahf primary key (id);
