[#ftl]
[@b.head/]
[@b.toolbar title="计划任务信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(cronJob) theme="list"]
    [@b.textfield name="cronJob.name" label="名称" value="${cronJob.name!}" required="true" maxlength="100"/]
    [@b.textfield name="cronJob.target" label="目标" value="${cronJob.target!}" required="true" maxlength="500" comment="执行目标类或地址"/]
    [@b.textarea name="cronJob.description" label="描述" value="${cronJob.description!}" cols="60" rows="2" maxlength="500"/]
    [@b.textarea name="cronJob.contents" label="任务内容" value="${cronJob.contents!}" cols="60" rows="6" maxlength="2000"/]
    [@b.textfield name="cronJob.expression" label="Cron表达式" value="${cronJob.expression!}" required="true" maxlength="100" comment="如: 0 0 2 * * ? 表示每天凌晨2点"/]
    [@b.radios name="cronJob.enabled" label="是否启用" value=cronJob.enabled! items="true:启用,false:禁用"/]
    [#if cronJob.persisted]
    [@b.field label="上次执行时间"]${(cronJob.lastExecuteAt?string("yyyy-MM-dd HH:mm:ss"))!'-'}[/@]
    [@b.field label="执行耗时"]
      [#if cronJob.duration??]${cronJob.duration.toMillis}毫秒[#else]-[/#if]
    [/@]
    [/#if]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
