[#ftl]
[@b.head/]
[@b.grid items=cronJobs var="cronJob"]
  [@b.gridbar]
    bar.addItem("${b.text("action.new")}",action.add());
    bar.addItem("${b.text("action.modify")}",action.edit());
    bar.addItem("${b.text("action.delete")}",action.remove("确认删除?"));
  [/@]
  [@b.row]
    [@b.boxcol/]
    [@b.col width="15%" property="name" title="名称"]
      [@b.a href="!info?id=${cronJob.id}" title="查看详情"]${cronJob.name}[/@]
    [/@]
    [@b.col width="20%" property="target" title="目标"/]
    [@b.col width="25%" property="expression" title="Cron表达式"/]
    [@b.col width="10%" title="状态"]
      [#if cronJob.enabled]启用[#else]禁用[/#if]
    [/@]
    [@b.col width="15%" property="lastExecuteAt" title="上次执行时间"/]
    [@b.col width="10%" title="耗时"]
      [#if cronJob.duration??]${cronJob.duration.toMillis}ms[#else]-[/#if]
    [/@]
  [/@]
[/@]
[@b.foot/]
