[#ftl]
[@b.head/]
[@b.toolbar title="计划任务信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(task) theme="list"]
    [@b.textfield name="task.name" label="名称" value=task.name! required="true" maxlength="100"/]
    [@b.textfield name="task.target" label="目标" value=task.target! required="true" maxlength="500" comment="localhost或者user@server_ip:port"/]
    [@b.textfield name="task.command" label="任务内容" value=task.command!  maxlength="500" required="true"  style="width:500px;"/]
    [@b.textarea name="task.description" label="描述" value=task.description! cols="60" rows="2" required="true"  maxlength="500"/]
    [@b.textfield name="task.expression" label="Cron表达式" value=task.expression! required="true" maxlength="100"]
      如: 0 0 2 * * ? 表示每天凌晨2点,参考 <a href="https://tool.lu/crontab/" target="_blank">在线工具中的sping配置</a>
    [/@]
    [@b.radios name="task.enabled" label="是否启用" value=task.enabled! items="true:启用,false:禁用"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
