[#ftl]
[@b.head/]
[@b.grid items=tasks var="task"]
  [@b.gridbar]
    bar.addItem("${b.text("action.new")}",action.add());
    bar.addItem("${b.text("action.modify")}",action.edit());
    bar.addItem("${b.text("action.delete")}",action.remove("确认删除?"));
  [/@]
  [@b.row]
    [@b.boxcol/]
    [@b.col width="15%" property="name" title="名称"]
      [@b.a href="!info?id=${task.id}" title="查看详情"]${task.name}[/@]
    [/@]
    [@b.col width="15%" property="target" title="目标"/]
    [@b.col width="10%" property="expression" title="Cron表达式"/]
    [@b.col property="description" title="描述"/]
    [@b.col width="7%" title="状态"]
      [#if task.enabled]启用[#else]禁用[/#if]
    [/@]
    [@b.col width="12%" property="lastExecuteAt" title="上次执行时间"/]
    [@b.col width="8%" title="耗时"]
      [#if task.duration??]${task.duration.toSeconds}s[#else]-[/#if]
    [/@]
  [/@]
[/@]
[@b.foot/]
