[#ftl]
[@b.head/]
[@b.toolbar title="计划任务执行日志"]bar.addBack();[/@]
  [@b.form action=b.rest.save(cronJobLog) theme="list"]
    [@b.select name="cronJobLog.job.id" label="计划任务" value=cronJobLog.job! items=cronJobs option="id,name" required="true"/]
    [@b.datetime name="cronJobLog.executeAt" label="执行时间" value=cronJobLog.executeAt! required="true"/]
    [#assign durationVal = ""]
    [#if cronJobLog.duration??]
      [#assign durationVal = cronJobLog.duration.toMillis?c]
    [/#if]
    [@b.textfield name="durationMillis" label="耗时(毫秒)" value=durationVal maxlength="20" comment="执行耗时，单位毫秒"/]
    [@b.select name="cronJobLog.statusCode" label="状态" value=cronJobLog.statusCode! items="0:成功,1:失败,2:运行中"/]
    [@b.textfield name="cronJobLog.resultFilePath" label="结果文件路径" value=(cronJobLog.resultFilePath.orElse(''))! maxlength="500"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
