[#ftl]
  [@b.nav class="nav-tabs nav-tabs-compact"]
    [@b.navitem href="user"]账户管理[/@]
    [@b.navitem href="role"]角色管理[/@]
    [@b.navitem href="group"]用户组管理[/@]
    [#if isRoot!false][@b.navitem href="root"]超级用户[/@][/#if]
  [/@]
