[#ftl]
[@b.head/]
[@b.toolbar title="修改用户"]bar.addBack("${b.text("action.back")}");[/@]
[@b.messages/]
[@b.tabs id="userinfotabs"]
  [@b.tab label="账户信息"]
    [@b.form name="accountForm" action="!update" class="listform" theme="list"]
        [#assign user=account.user/]
        [@b.textfield name="user.code" value=user.code style="width:200px;" required="true" maxlength="30"/]
        [@b.textfield name="user.name" value=user.name  style="width:200px;" required="true" maxlength="30"/]
        [@b.select name="user.category.id" label="身份" value=user.category! items=categories required="true"/]
        [@b.cellphone name="user.mobile" value=user.mobile! /]
        [@b.email name="user.email" value=user.email! /]
        [@b.radios name="account.enabled" value=account.enabled items="1:action.activate,0:action.freeze"/]
        [@b.radios name="account.locked" value=account.locked items="1:锁定,0:解锁"/]
        [@b.password label="account.password" name="password" value="" maxlength="20" showStrength="true"/]
        [@b.startend label="有效期" name="account.beginOn,account.endOn" required="true,false" start=account.beginOn end=account.endOn format="date" comment="过期后不能登录"/]
        [@b.date name="account.passwdExpiredOn" value=account.passwdExpiredOn format="date"  required="true" comment="过期后，仍可登录，但需要及时更新密码。"/]
        [@b.textarea cols="50" rows="1" name="user.remark" value=user.remark! maxlength="50"/]
        [@b.formfoot]
          <input type="hidden" name="user.id" value="${user.id}" />
          [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
        [/@]
    [/@]
  [/@]
  [@b.tab label="角色"]
  [@b.form name="memberForm" action="!saveRole" class="listform" theme="list"]
    [@b.grid  items=roles?sort_by("indexno") var="role" sortable="false"]
      [@b.row]
        <tr [#if role??]id="${role.indexno}"[/#if]>
        [@b.col title="common.index" width="5%"]${role_index+1}[/@]
        [@b.treecol title="角色" property="name"]
          <span [#if !role.enabled]class="ui-disabled" title="${b.text('action.freeze')}"[/#if]>
          ${role.indexno} ${role.name}[#if !role.enabled] (禁用)[/#if]
          </span>
        [/@]
        [@b.col title="成员" width="10%"]
          [#assign displayMember=(role.enabled && mngMemberMap.get(role).granter)/]
          <input type="checkbox" class="security_member" [#if !displayMember]style="display:none"[/#if] name="member${role.id}" ${(memberMap.get(role).member)?default(false)?string('checked="checked"','')}/>
          [#if !displayMember && (memberMap.get(role).member)!false]&radic;[/#if]
        [/@]
        [@b.col title="可授权" width="10%"]
          [#assign displayGranter=(role.enabled && mngMemberMap.get(role).granter)/]
          <input type="checkbox" name="granter${role.id}" [#if !displayGranter]style="display:none"[/#if] ${(memberMap.get(role).granter)?default(false)?string('checked="checked"','')}/>
          [#if !displayGranter && (memberMap.get(role).granter)!false]&radic;[/#if]
        [/@]
        [@b.col title="可管理" width="10%"]
          [#assign displayManager=(role.enabled && mngMemberMap.get(role).manager)/]
          <input type="checkbox" name="manager${role.id}" [#if !displayManager]style="display:none"[/#if] ${(memberMap.get(role).manager)?default(false)?string('checked="checked"','')}/>
          [#if !displayManager && (memberMap.get(role).manager)!false]&radic;[/#if]
        [/@]
        [@b.col title="common.updatedAt" width="20%"]${(memberMap.get(role).updatedAt)!}[/@]
        </tr>
      [/@]
    [/@]
    [@b.formfoot]
       <input type="hidden" name="user.id" value="${user.id!}" />
        [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
      [/@]
  [/@]
[/@]
  [#if user.persisted]
  [@b.tab label="全局数据权限" ]
  [@b.div href="/admin/user/profile?forEdit=1&profile.user.id=${user.id}" /]
  [/@]
  [/#if]
[/@]
[@b.foot/]
