create schema ems;

alter table blb.blob_metas set schema ems;
alter table blb.profiles set schema ems;
alter table cfg.app_groups set schema ems;
alter table cfg.app_types set schema ems;
alter table cfg.apps set schema ems;
alter table cfg.credentials set schema ems;
alter table cfg.data_sources set schema ems;
alter table cfg.dbs set schema ems;
alter table cfg.dbs_properties set schema ems;
alter table cfg.domains set schema ems;
alter table cfg.files set schema ems;
alter table cfg.orgs set schema ems;
alter table cfg.portalets set schema ems;
alter table cfg.portalets_categories set schema ems;
alter table log.business_logs set schema ems;
alter table log.levels set schema ems;
alter table log.session_events set schema ems;
alter table oa.docs set schema ems;
alter table oa.docs_user_categories set schema ems;
alter table oa.messages set schema ems;
alter table oa.news set schema ems;
alter table oa.notices set schema ems;
alter table oa.notices_user_categories set schema ems;
alter table oa.notices_docs set schema ems;
alter table oa.notifications set schema ems;
alter table usr.notifications set schema ems;
alter table oa.sensitive_words set schema ems;
alter table oa.todoes set schema ems;
alter table usr.todoes set schema ems;
alter table se.app_permissions set schema ems;
alter table se.data_permissions set schema ems;
alter table se.data_resources set schema ems;
alter table se.func_permissions set schema ems;
alter table se.func_resources set schema ems;
alter table se.menus set schema ems;
alter table se.menus_resources set schema ems;
alter table usr.accounts set schema ems;
alter table usr.avatars set schema ems;
alter table usr.user_categories set schema ems;
alter table usr.dimensions set schema ems;
alter table usr.group_members set schema ems;
alter table usr.user_groups set schema ems;
alter table usr.user_groups_properties set schema ems;
alter table usr.password_configs set schema ems;
alter table usr.user_profiles set schema ems;
alter table usr.user_profiles_properties set schema ems;
alter table usr.role_members set schema ems;
alter table usr.roles_properties set schema ems;
alter table usr.roots set schema ems;
alter table usr.roles set schema ems;
alter table usr.users set schema ems;
alter table ssn.session_configs set schema ems;
alter table ssn.session_infoes set schema ems;

alter table ems.blob_metas rename to blb_blob_metas;
alter table ems.profiles rename to blb_profiles;
alter table ems.app_groups rename to cfg_app_groups;
alter table ems.app_types rename to cfg_app_types;
alter table ems.apps rename to cfg_apps;
alter table ems.credentials rename to cfg_credentials;
alter table ems.data_sources rename to cfg_data_sources;
alter table ems.dbs rename to cfg_dbs;
alter table ems.dbs_properties rename to cfg_dbs_properties;
alter table ems.domains rename to cfg_domains;
alter table ems.files rename to cfg_files;
alter table ems.orgs rename to cfg_orgs;
alter table ems.portalets rename to cfg_portalets;
alter table ems.portalets_categories rename to cfg_portalets_categories;
alter table ems.business_logs rename to log_business_logs;
alter table ems.levels rename to log_levels;
alter table ems.session_events rename to log_session_events;
alter table ems.docs rename to oa_docs;
alter table ems.docs_user_categories rename to oa_docs_categories;
alter table ems.messages rename to oa_messages;
alter table ems.news rename to oa_news;
alter table ems.notices rename to oa_notices;
alter table ems.notices_user_categories rename to oa_notices_categories;
alter table ems.notices_docs rename to oa_notices_docs;
alter table ems.notifications rename to oa_notifications;
alter table ems.sensitive_words rename to oa_sensitive_words;
alter table ems.todoes rename to oa_todoes;
alter table ems.app_permissions rename to se_app_permissions;
alter table ems.data_permissions rename to se_data_permissions;
alter table ems.data_resources rename to se_data_resources;
alter table ems.func_permissions rename to se_func_permissions;
alter table ems.func_resources rename to se_func_resources;
alter table ems.menus rename to se_menus;
alter table ems.menus_resources rename to se_menus_resources;
alter table ems.accounts rename to usr_accounts;
alter table ems.avatars rename to usr_avatars;
alter table ems.user_categories rename to usr_categories;
alter table ems.dimensions rename to usr_dimensions;
alter table ems.group_members rename to usr_group_members;
alter table ems.user_groups rename to usr_groups;
alter table ems.user_groups_properties rename to usr_groups_properties;
alter table ems.password_configs rename to usr_password_configs;
alter table ems.user_profiles rename to usr_profiles;
alter table ems.user_profiles_properties rename to usr_profiles_properties;
alter table ems.role_members rename to usr_role_members;
alter table ems.roles_properties rename to usr_roles_properties;
alter table ems.roots rename to usr_roots;
alter table ems.roles rename to usr_roles;
alter table ems.users rename to usr_users;
alter table ems.session_configs rename to se_session_configs;
alter table ems.session_infoes rename to se_session_infoes;

alter view blb.domains rename to blb_domains;
alter view blb.users rename to blb_users;
alter view blb.blb_domains set schema ems;
alter view blb.blb_users set schema ems;

drop table usr.users_properties;

drop schema cfg;
drop schema log;
drop schema oa;
drop schema se;
drop schema usr;
drop schema ssn cascade;
drop schema blb;

alter table ems.cfg_portalets_categories rename user_category_id to category_id;
alter table ems.oa_docs_categories rename user_category_id to category_id;
alter table ems.oa_notices_categories rename user_category_id to category_id;

alter table ems.usr_profiles_properties rename user_profile_id to profile_id;
alter table ems.cfg_files add constraint uk_c7cyjywlvbtlmsdanw03y0syi unique (app_id,name);
