alter table ems.blb_blob_metas add constraint pk_b8cqbowbec39t4blmd3n8n074 primary key (id);
alter table ems.blb_blob_metas add constraint uk_6f0sq8k4w2vuw9r5qhdy1tjud unique (profile_id,file_path);
alter table ems.blb_profiles add constraint pk_4xq2aas8pre2k4gnyha4rrdc6 primary key (id);
alter table ems.cfg_app_groups add constraint idx_app_group unique (domain_id,name);
alter table ems.cfg_app_groups add constraint pk_j2j2ecvy0xos5dyc5bpvukvoo primary key (id);
alter table ems.cfg_app_types add constraint pk_tlb9nukbd5nakxiqdrb4lrrkg primary key (id);
alter table ems.cfg_app_types add constraint uk_5qmq81gd1xna4xeynxkdueqgu unique (name);
alter table ems.cfg_apps add constraint idx_app unique (domain_id,name);
alter table ems.cfg_apps add constraint pk_n9cedywnexu7mm5vrohyngxhi primary key (id);
alter table ems.cfg_businesses add constraint pk_1gjbnmsu7g40waqd6fhqyvhg7 primary key (id);
alter table ems.cfg_credentials add constraint idx_credential unique (domain_id,name);
alter table ems.cfg_credentials add constraint pk_jqt3pjl6myepf89yf4vpl69lv primary key (id);
alter table ems.cfg_data_sources add constraint idx_datasource unique (app_id,name);
alter table ems.cfg_data_sources add constraint pk_hbg82rakrkc2sifjhhimm05p2 primary key (id);
alter table ems.cfg_dbs add constraint idx_db unique (domain_id,name);
alter table ems.cfg_dbs add constraint pk_60bu45dxjo2fv64icid8g60dr primary key (id);
alter table ems.cfg_dbs add constraint uk_knjsj49986iis6p9nfvlrink6 unique (name);
alter table ems.cfg_dbs_properties add constraint pk_4hn9p4sx2tba0kn8c5m68bn5e primary key (db_id,value_,name);
alter table ems.cfg_domains add constraint idx_domain unique (org_id,hostname);
alter table ems.cfg_domains add constraint pk_endu524c1sjo6rfnwll8j7lgl primary key (id);
alter table ems.cfg_domains add constraint uk_4acqortg7kuo0b9i3cnefdct1 unique (name);
alter table ems.cfg_domains add constraint uk_prodovqul9i18esekttaynh92 unique (hostname);
alter table ems.cfg_files add constraint pk_mqdje4swyctoaf3fghs8nh2h0 primary key (id);
alter table ems.cfg_files add constraint uk_c7cyjywlvbtlmsdanw03y0syi unique (app_id,name);
alter table ems.cfg_orgs add constraint pk_p2falj90tsjnuf6cul4dtnwbr primary key (id);
alter table ems.cfg_orgs add constraint uk_ry9aq5agfqx7nvjg1j7mh7ejl unique (code);
alter table ems.cfg_portalets add constraint pk_lusy0ot4df8ad2ogi52ud31x0 primary key (id);
alter table ems.cfg_portalets_categories add constraint pk_3y5ll75dv63sbfxrt5djc3vst primary key (portalet_id,category_id);
alter table ems.cfg_rule_metas add constraint pk_luomjgmjug1xl0nepih2e6bp7 primary key (id);
alter table ems.cfg_rule_param_metas add constraint pk_72klsho25nxj48adlsbsvxw24 primary key (id);
alter table ems.cfg_rule_params add constraint pk_ohdu0agjno63noube9jnd03x2 primary key (id);
alter table ems.cfg_rules add constraint pk_nqb0kg717ty66bcdlbevgg40w primary key (id);
alter table ems.cfg_text_bundles add constraint pk_7ckmfs80yl3vy0rb4h5kw0wy7 primary key (id);
alter table ems.cfg_themes add constraint pk_8cgpd1jxx29su0g416k4uqq7h primary key (id);
alter table ems.cfg_third_party_apps add constraint pk_rrfs9bcq1gl1dhw3894kitrn5 primary key (id);
alter table ems.jb_cron_task_logs add constraint pk_11be0fdugwgb8ikd3di6piful primary key (id);
alter table ems.jb_cron_tasks add constraint idx_cron_task unique (domain_id,name);
alter table ems.jb_cron_tasks add constraint pk_ekeyej7cs8cyenoef6fjv6qo8 primary key (id);
alter table ems.oa_docs add constraint pk_fc7xgtw2ph01nxnly6xdjj2ck primary key (id);
alter table ems.oa_docs_categories add constraint pk_t2xiuni4rx9kqxk3tl6ho27m0 primary key (doc_id,category_id);
alter table ems.oa_done_todoes add constraint pk_mn26km960qlp4vdudumww56lb primary key (id);
alter table ems.oa_flow_active_processes add constraint pk_samobwkymr25sieibooxk8i82 primary key (id);
alter table ems.oa_flow_active_tasks add constraint pk_le4po92kywf3ojowai32ckn4y primary key (id);
alter table ems.oa_flow_active_tasks_assignees add constraint pk_d6macidl90syk0lcjblvyr8cx primary key (flow_active_task_id,user_id);
alter table ems.oa_flow_activities add constraint pk_65sx3h9xpdmkd2fh6taiqct3x primary key (id);
alter table ems.oa_flow_activities_groups add constraint pk_bu5sb3dylrw46u4nevi81m7g3 primary key (flow_activity_id,group_id);
alter table ems.oa_flow_attachments add constraint pk_l0ch5m00xqxxosy5tbglcb29e primary key (id);
alter table ems.oa_flow_comments add constraint pk_r28qro3eeiewfaid733wom7vi primary key (id);
alter table ems.oa_flow_processes add constraint pk_a4vw1icdpl9fd0lidn46ov43x primary key (id);
alter table ems.oa_flow_tasks add constraint pk_ix1l2ynxneogn9xxg9poq7q0k primary key (id);
alter table ems.oa_flows add constraint pk_a73xr38hwrn5eq0cms9vtaojj primary key (id);
alter table ems.oa_message_templates add constraint pk_ns2rk4q0gl4ls5ctn6j6j1b38 primary key (id);
alter table ems.oa_messages add constraint pk_72sarmx45o88vbj3vxqpxxuic primary key (id);
alter table ems.oa_news add constraint pk_eal2o84cuiediaeu3jpbj2rw8 primary key (id);
alter table ems.oa_notices add constraint pk_fd9lrfm32gdx34wnf5tkegwri primary key (id);
alter table ems.oa_notices_categories add constraint pk_ptniioqdxghbgxfb5nuxa8sok primary key (notice_id,category_id);
alter table ems.oa_notices_docs add constraint pk_g1q8sxttj2f38br6tshq0oyop primary key (notice_id,doc_id);
alter table ems.oa_sensitive_words add constraint pk_pjoqu9l57q76r8j9m8ohsd7bv primary key (id);
alter table ems.oa_signatures add constraint pk_dfbyistwcn4ddt5f4967c4lp4 primary key (id);
alter table ems.oa_signatures add constraint uk_hk2c47ht0vh6ti15lnfmvfxc9 unique (user_id);
alter table ems.oa_todoes add constraint pk_9miwvbk7lnym5j8gloxvye2ov primary key (id);
alter table ems.se_app_permissions add constraint pk_d4wk578yt4vxs2wsxqw6wi44r primary key (id);
alter table ems.se_data_permissions add constraint pk_n3ngio8x079e9p038kn9208we primary key (id);
alter table ems.se_data_resources add constraint pk_m2lwng0xtvh944i0suv865sy primary key (id);
alter table ems.se_func_permissions add constraint pk_2oifsqty75lclhgfdusglmk4d primary key (id);
alter table ems.se_func_resources add constraint pk_glt9bssuurgayvpnxjupcsfqm primary key (id);
alter table ems.se_menus add constraint pk_c3931pkfbpf3uerudht53n8sj primary key (id);
alter table ems.se_menus_resources add constraint pk_gtyin0ge9irq6gy8qoupwbf3j primary key (menu_id,func_resource_id);
alter table ems.se_session_configs add constraint idx_session_config unique (domain_id,category_id);
alter table ems.se_session_configs add constraint pk_pp3vns65x9utg2vwtogp2cao8 primary key (id);
alter table ems.usr_avatars add constraint pk_evhoecg5aoxqjlhw3emfuevip primary key (id);
alter table ems.usr_categories add constraint idx_user_category unique (org_id,name);
alter table ems.usr_categories add constraint pk_j6l4jh94s3ga3ncv15fg7kjl4 primary key (id);
alter table ems.usr_categories add constraint uk_355dgck69qve4mlsk1d2dow4q unique (code);
alter table ems.usr_departs add constraint pk_lqtwc4myrcgfw4e69xam0gx17 primary key (id);
alter table ems.usr_dimensions add constraint idx_dimension_name unique (domain_id,name);
alter table ems.usr_dimensions add constraint pk_17npsfcux6ix6kjq7r73roe2i primary key (id);
alter table ems.usr_group_members add constraint pk_9kgi9t31dhattii415hnqa8wp primary key (id);
alter table ems.usr_group_members add constraint uk_eybgaja399psr9ld03vd1cm70 unique (group_id,user_id);
alter table ems.usr_groups add constraint idx_group unique (org_id,code);
alter table ems.usr_groups add constraint pk_qiobgfi5x9uer99bb4an2klr5 primary key (id);
alter table ems.usr_groups_roles add constraint pk_sb7917p9v5v4yodepe7kflr3s primary key (group_id,role_id);
alter table ems.usr_password_configs add constraint idx_password_config unique (domain_id);
alter table ems.usr_password_configs add constraint pk_5qffiflvujhi6qpd4ww3doin5 primary key (id);
alter table ems.usr_profiles add constraint pk_l9sqo0uv1apeypxv0k3qchf8k primary key (id);
alter table ems.usr_profiles_properties add constraint pk_8erccmnnign5i91qbu5tpffw9 primary key (profile_id,value_,dimension_id);
alter table ems.usr_role_members add constraint pk_1vq74b9ympc9qdgjvqcghk84e primary key (id);
alter table ems.usr_roles add constraint idx_role_name unique (domain_id,name);
alter table ems.usr_roles add constraint pk_237n7fw14i3w0u34cwhapigb0 primary key (id);
alter table ems.usr_roles_properties add constraint pk_59m7apft4dpohfgp900cbkkip primary key (role_id,value_,dimension_id);
alter table ems.usr_roots add constraint pk_gpdqluxdt236rx6ft5wdoxiix primary key (id);
alter table ems.usr_users add constraint idx_user_code unique (org_id,code);
alter table ems.usr_users add constraint pk_q9yqro8mq11gawulqm149lahf primary key (id);
alter table log.ems_business_logs add constraint pk_n6v1mxbrbc6tw6mvyh4cqy9uq primary key (id);
alter table log.ems_error_logs add constraint pk_5n4ch46jn9kkurc26ykg20hbw primary key (id);
alter table log.ems_session_events add constraint pk_oe05752qmg0omw08pxvms0e00 primary key (id);
