[#ftl]
[@b.head/]
[@b.toolbar title="修改部件"]bar.addBack();[/@]
[@b.form action=b.rest.save(portalet) theme="list"]
  [@b.textfield name="portalet.idx" required="true" label="顺序号" value=portalet.idx! maxlength="5"/]
  [@b.textfield name="portalet.name" required="true" label="common.name" value=portalet.name! maxlength="50"/]
  [@b.textfield name="portalet.title" required="true" label="标题" value=portalet.title! maxlength="50" /]
  [@b.number name="portalet.rowIndex" required="true" label="行" value=portalet.rowIndex! max="5" min="1" comment="1～5" /]
  [@b.number name="portalet.colspan" required="true" label="列数" value=portalet.colspan! max="12" min="1" comment="1～12" /]
  [@b.textfield name="portalet.url" required="true" label="网址" value=portalet.url! maxlength="200"  style="width:400px"/]
  [@b.radios label="集成方式" name="portalet.usingIframe"  items="1:Iframe,0:Div" value=portalet.usingIframe /]
  [@b.select label="面向用户" name="category.id" multiple="true" items=categories values=portalet.categories chosenMin="1"  style="width:400px"/]
  [@b.radios label="是否可用" name="portalet.enabled" value=portalet.enabled  items="1:是,0:否"/]
  [@b.formfoot]
    [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
  [/@]
[/@]
<br><br><br><br>
[@b.foot/]
