[#ftl]
[@b.head/]
[@b.toolbar title="新建/修改业务文件配置"]bar.addBack();[/@]
[@b.form action=b.rest.save(profile) title="修改业务文件配置" theme="list"]
  [@b.textfield name="profile.name" required="true" label="common.name" value="${profile.name!}" maxlength="50" style="width:250px"/]
  [@b.textfield name="profile.base" required="true" label="路径" value="${profile.base!}" maxlength="50"  comment="路径唯一"/]
  [@b.radios label="按照sha命名" name="profile.namedBySha"  items="1:是,0:否" value= profile.namedBySha /]
  [@b.radios label="文件公开下载" name="profile.publicDownload" value=profile.publicDownload  items="1:是,0:否"/]
  [@b.select label="可写应用" name="app.id"  items=apps values=profileApps option="id,title" required="false" multiple="true"/]
  [@b.formfoot]
    [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
  [/@]
[/@]
[#list 1..10 as i]<br>[/#list]
[@b.foot/]
