[#ftl]
[@b.head/]
[@b.toolbar title="新建/修改业务文件配置"]bar.addBack();[/@]
[@b.form action=b.rest.save(profile) title="修改业务文件配置" theme="list"]
  [@b.textfield name="profile.name" required="true" label="common.name" value="${profile.name!}" maxlength="50" style="width:250px"/]
  [@b.textfield name="profile.base" required="true" label="路径" value="${profile.base!}" maxlength="50"  comment="路径唯一"/]
  [@b.formfoot]
    [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
  [/@]
[/@]
[#list 1..10 as i]<br>[/#list]
[@b.foot/]
