[#ftl]
[@b.head/]
[@b.toolbar title="修改应用"]bar.addBack();[/@]
<style>form.listform label.title{width:120px;}</style>
  [@b.form action=b.rest.save(app) theme="list"]
    [@b.field label="所属域"]${domainDisplayName!}[/@]
    [@b.textfield name="app.code" label="代码" value=app.code! required="true" maxlength="50"/]
    [@b.textfield name="app.name" label="名称" value=app.name! required="true" maxlength="100"  style="width:200px"/]
    [@b.textfield name="app.secret" label="密钥" value=app.secret! required="true" maxlength="100" style="width:300px"/]
    [@b.textfield name="app.redirectUri" label="回调地址" value=app.redirectUri! maxlength="500" style="width:500px" required="true"  comment="OAuth 等场景的重定向 URI"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
